version: '3.8'

networks:
  popscope_network:
    driver: bridge

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - FILE_PATH=/app/country_development.tsv
    networks:
      - popscope_network

  frontend:
    build:
      context: ./platform
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always 
    environment:
      - API_BASE_URL=https://api.dogukangun.de/api
    networks:
      - popscope_network