version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - FILE_PATH=/app/country_development.tsv

  frontend:
    build:
      context: ./platform
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always 
    environment:
      - API_BASE_URL=http://localhost:8080/api